# Generated by Django 3.0.3 on 2020-04-27 17:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200427_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 27, 17, 12, 52, 436154, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='Create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 27, 17, 12, 52, 434154, tzinfo=utc)),
        ),
    ]
